name: checkCI

on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11'  
        
        - name: run test
          run: |
            python -m unittest discover -s . -p "test.py"
        
        - name: Zip it
          run : |
            zip -r project.zip      




